stages:
  - deploy

pages:
  stage: deploy
  image: node:20
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
  variables:
    PAGES_PREFIX: ""
  script:
    - npm ci --prefer-offline --no-audit --fund=false
    - npm run build
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  pages:
    path_prefix: "$PAGES_PREFIX"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        PAGES_PREFIX: ""
        VITE_PAGES_PREFIX: ""
        VITE_BRANCH: "main"
    - if: '$CI_COMMIT_BRANCH != "main"'
      variables:
        PAGES_PREFIX: "$CI_COMMIT_REF_SLUG"
        VITE_PAGES_PREFIX: "$CI_COMMIT_REF_SLUG"
        VITE_BRANCH: "$CI_COMMIT_REF_NAME"


